/*----------------------------------------------------------
MASV: 20127072
HO TEN: Lê Võ Huỳnh Thanh
LAB: 03
----------------------------------------------------------*/

--a. TAO DB
USE master
GO
IF DB_ID('QLSV') IS NOT NULL
	DROP DATABASE QLSV
GO
CREATE DATABASE QLSV
GO

--b. CAC CAU LENH TAO TABLE
USE QLSV
GO
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL

	CONSTRAINT PK_SV
	PRIMARY KEY(MASV)
)
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL

	CONSTRAINT PK_NV
	PRIMARY KEY(MANV)
)
CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)

	CONSTRAINT PK_LOP
	PRIMARY KEY(MALOP)
)

--c. CAU LENH TAO STORED PROCEDURE
-- i. Insert vào table SINHVIEN, hash MATKHAU bằng MD5
if OBJECT_ID('SP_INS_SINHVIEN') is not null
	drop proc SP_INS_SINHVIEN
go
CREATE PROCEDURE SP_INS_SINHVIEN @MaSV NVARCHAR(20), @HoTen NVARCHAR(100), @NgaySinh DATETIME, 
								@DiaChi NVARCHAR(200), @MaLop VARCHAR(20), @TenDN NVARCHAR(100),
								@MatKhau VARCHAR(MAX)
AS
	DECLARE @hash_pass VARBINARY(MAX)
	SET @hash_pass = HASHBYTES('MD5', @MatKhau)
	INSERT SINHVIEN VALUES(@MaSV, @HoTen, @NgaySinh, @DiaChi, @MaLop, @TenDN, @hash_pass)

EXEC SP_INS_SINHVIEN N'SV01', N'NGUYEN VAN A', '1/1/1990', N'280 AN DUONG VUONG', 'CNTT-K35', N'NVA', '123456'
select * from SINHVIEN
GO


-- I. Thiết lập để sử dụng mã hoá đối xứng AES_256
-- Tạo master key
IF NOT EXISTS
(
	SELECT *
	FROM sys.symmetric_keys
	WHERE symmetric_key_id = 101
)
CREATE MASTER KEY ENCRYPTION BY
	PASSWORD = '20127072'
GO
-- Tạo certificate
IF NOT EXISTS
(
	SELECT *
	FROM sys.certificates
	WHERE name = 'MyCert'
)
CREATE CERTIFICATE MyCert WITH SUBJECT = 'MyCert'
GO
--Tạo private key
IF NOT EXISTS
(
	SELECT *
	FROM sys.symmetric_keys
	WHERE name = 'PriKey'
)
CREATE SYMMETRIC KEY PriKey WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE MyCert
GO
--Mã hoá dữ liệu (lương) sử dụng AES256
OPEN SYMMETRIC KEY PriKey
DECRYPTION BY CERTIFICATE MyCert

-- (ii). Thêm dữ liệu vào bảng NHANVIEN, MATKHAU -> SHA1, LUONG -> AES(256, MSSV)
if OBJECT_ID('SP_INS_NHANVIEN') is not null
	drop proc SP_INS_NHANVIEN
go
CREATE PROCEDURE SP_INS_NHANVIEN @MaNV VARCHAR(20), @HoTen NVARCHAR(100), @email VARCHAR(20),
								@luong INT, @TenDN NVARCHAR(100), @MatKhau VARCHAR(MAX)
AS
	DECLARE @encrypted_luong VARBINARY(MAX)
	SET @encrypted_luong = (SELECT ENCRYPTBYKEY(KEY_GUID('PriKey'), CONVERT(VARCHAR(MAX), @luong)))
	
	DECLARE @hash_pass VARBINARY(MAX)
	SET @hash_pass = HASHBYTES('SHA1', @MatKhau)

	INSERT NHANVIEN VALUES(@MaNV, @HoTen, @email, @encrypted_luong, @TenDN, @hash_pass)

EXEC SP_INS_NHANVIEN N'NV01', N'NGUYEN VAN A', 'NVA@', 3000000, N'NVA', 'abcd12'
select * from NHANVIEN
GO

-- (iii). Truy vấn dữ liệu nhân viên
IF OBJECT_ID('SP_SEL_NHANVIEN') IS NOT NULL
	DROP PROCEDURE SP_SEL_NHANVIEN
GO
CREATE PROCEDURE SP_SEL_NHANVIEN
AS
	SELECT MANV, HOTEN, EMAIL, CAST(CONVERT(VARCHAR(MAX), DECRYPTBYKEY(LUONG)) AS INT) as LUONGCB FROM NHANVIEN

EXEC SP_SEL_NHANVIEN
GO

